import java.util.*;
import java.math.BigInteger; 
import java.nio.charset.StandardCharsets; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
class SHA256{ 
	public static byte[] getSHA(String input) throws NoSuchAlgorithmException 
	{ 
		MessageDigest md = MessageDigest.getInstance("SHA-256"); 
		return md.digest(input.getBytes(StandardCharsets.UTF_8)); 
	} 
	
	public static String toHexString(byte[] hash) 
	{ 
		BigInteger number = new BigInteger(1, hash); 
		StringBuilder hexString = new StringBuilder(number.toString(16)); 
		while (hexString.length() < 32) 
		{ 
			hexString.insert(0, '0'); 
		} 

		return hexString.toString(); 
	} 

	public static void main(String args[]) 
	{ 
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter Text");
		try
		{ 
			String s1 = sc.nextLine();
			System.out.println("HashCode Generated by SHA-256 for:"); 
			System.out.println("\n" + s1 + " : " + toHexString(getSHA(s1))); 

		}catch (Exception e) { e.printStackTrace();} 
	} 
} 
